#!/bin/bash

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.200  netmask 255.255.255.0  broadcast 0.0.0.0
        inet6 fe80::64f5:dfdf:35c3:6338  prefixlen 128  scopeid 0x20<link>
        ether 3c:97:0e:98:bd:35  txqueuelen 1000  (Ethernet)
        RX packets 1920043  bytes 562086835 (536.0 MiB)
        RX errors 0  dropped 2  overruns 0  frame 0
        TX packets 1285027  bytes 102694193 (97.9 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 19  

ifconfig eth1 192.168.2.1 netmask 255.255.255.0 up






